### ISSUE TITLE
Imported types issue

### ISSUE THREAD

**Issue by lakeshadow0** [supercharge/fs#14]
Importing this package appears to have a problem in Typescript related to references for `fs-extra` types, which are not installed with the package.

```ts
declare const _default: typeof Fs & { // _default is any here, removing typeof Fs fixes this
```

Installing `@types/fs-extra` directly into the package (within my node_modules) fixes this. I would assume, then, that moving the types packages from `devDependencies` to `dependencies` would fix this permanently.

**Comment by marcuspoehls** [comment]
Makes sense. Too bad the typings aren't resolved properly.

@lakeshadow0 Do you want to submit a pull request?

**Comment by marcuspoehls** [comment]
@lakeshadow0 I’ve tagged `3.0.1` and published it to NPM. Thank you for your help with this issue! I really appreciate it 👍
